### ISSUE TITLE
DBScan PointList and Center not filled

### ISSUE THREAD

**Issue by asturm-fe** [spatial-go/geoos#107]
I am currently looking into this library for its geospatial clustering capabilities.
I tried out the DBScan but noticed, that the `clusters.Cluster` properties `PointList` and `Center` are not filled.
It seems to me that the calls to `cluster.Append(Point)` and `cluster.Recenter()` are missing from the implementation of DBScan.
While I can do this manually after the clustering, I had expected this to be done inside the clustering function.

If this is unintentional, I suppose the changes would be easy enough to make so I could provide a MR - I look forward to your answer.

**Comment by xiaogu-space** [comment]
We will very pleased if you can provide MR
