### ISSUE TITLE
A problem of  the method space.Contains()

### ISSUE THREAD

**Issue by fonto86** [spatial-go/geoos#56]
While using the method `space.Contains()` to determine whether `Geometry A` contains `Geometry B`，I found that in some cases the result returned is not as expected. The code is as follows:

```go
type TestStruct struct {
	name    string
	args    args
	want    bool
	wantErr bool
}
func TestAlgorithm_Contains(t *testing.T) {
	const polygon1 = `POLYGON((1 1,5 1,5 5,1 5,1 1))`
	const polygon2 = `POLYGON((2 2,3 2,3 3,2 3,2 2))`

	p1, _ := wkt.UnmarshalString(polygon1)
	p2, _ := wkt.UnmarshalString(polygon2)

	tests := []TestStruct{
		{name: "contain", args: args{
			g1: p1,
			g2: p2,
		}, want: true, wantErr: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			G := NormalStrategy()
			got, err := G.Contains(tt.args.g1, tt.args.g2) // got = true
			if (err != nil) != tt.wantErr {
				t.Errorf("Contains() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("Contains() got = %v, want %v", got, tt.want)
			}
		})
	}
}
```

and the corresponding image is

<img src="https://yift-blog-1300051863.cos.ap-guangzhou.myqcloud.com/blog/image-20220118212319961.png" alt="image-20220118212319961" style="zoom: 50%;" />

obviously it is correct.

But when I change the parameters, where `polygon1 = POLYGON((113.48581807062143 23.33621329259057,113.48785155569199 23.336383160940287,113.48792833916376 23.335028970144833,113.48582512451681 23.33493907732756,113.48581807062143 23.33621329259057))` and `polygon2 = POLYGON((113.48668269733025 23.335774475286513,113.48720314737876 23.3358047169134,113.4873120145494 23.335572135724533,113.48676140749377 23.33538486387792,113.48668269733025 23.335774475286513))`，the result returned is false，but it should actually be `true`, as the image shows：

<img src="https://yift-blog-1300051863.cos.ap-guangzhou.myqcloud.com/blog/image-20220118213111364.png" alt="image-20220118213111364" style="zoom:50%;" />

I want to judge whether a POLYGON A contains another POLYGON B, but the result returned by this method does not match the actual one, or is there another more suitable way to judge? Hope someone can answer my doubts,thank you very much.

**Comment by xiaogu-space** [comment]
we will fix it in this pull requests,thanks for your issues
 https://github.com/spatial-go/geoos/pull/57

**Comment by Mamba2Yi** [comment]
> xiaogu-space

**Comment by fonto86** [comment]
> we will fix it in this pull requests,thanks for your issues #57

hi~the previous problem was fixed, but I found another problem while testing. When I tested using the following two polygons：

```go
func TestAlgorithm_Contains(t *testing.T) {
	// ...
	const polygon4 = `POLYGON ((277.0764427576214075 220.0703895697370172, 231.7694100104272366 422.7364493119530380, 361.1115263458341360 451.6569778039120138, 406.4185590930283070 248.9906205087900162, 277.0764427576214075 220.0703895697370172))`
	const polygon5 = `POLYGON ((157.0188155006617308 268.8332448475994170, 157.0188155006617308 403.2498672713991255, 314.0376310013234615 403.2498672713991255, 314.0376310013234615 268.8332448475994170, 157.0188155006617308 268.8332448475994170))`

	// ...
  
	poly4, _ := wkt.UnmarshalString(polygon4)
	poly5, _ := wkt.UnmarshalString(polygon5)

	tests := []TestStruct{
		// ...
		{name: "notcontain", args: args{
			g1: poly4,
			g2: poly5,
		}, want: false, wantErr: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			G := NormalStrategy()
			got, err := G.Contains(tt.args.g1, tt.args.g2)  // true
			if (err != nil) != tt.wantErr {
				t.Errorf("Contains() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("Contains() got = %v, want %v", got, tt.want)
			}
		})
	}
}
```

The result returned is `true`.

However, when I used a visualization tool for verification, I found that the results were wrong.

As `polygon4` shown in the pictures，

<img src="https://yift-blog-1300051863.cos.ap-guangzhou.myqcloud.com/blog/image-20220208111053447.png" alt="image-20220208111053447" style="zoom:50%;" />

and `polygon5` shown：

<img src="https://yift-blog-1300051863.cos.ap-guangzhou.myqcloud.com/blog/image-20220208111318482.png" alt="image-20220208111318482" style="zoom:50%;" />

The relationship between these 2 shapes is：

<img src="https://yift-blog-1300051863.cos.ap-guangzhou.myqcloud.com/blog/image-20220208111459125.png" alt="image-20220208111459125" style="zoom:50%;" />

Obviously `not contained`.


THX~

**Comment by xiaogu-space** [comment]
> > we will fix it in this pull requests,thanks for your issues #57
> 
> hi~the previous problem was fixed, but I found another problem while testing. When I tested using the following two polygons：
> 
> ```go
> func TestAlgorithm_Contains(t *testing.T) {
> 	// ...
> 	const polygon4 = `POLYGON ((277.0764427576214075 220.0703895697370172, 231.7694100104272366 422.7364493119530380, 361.1115263458341360 451.6569778039120138, 406.4185590930283070 248.9906205087900162, 277.0764427576214075 220.0703895697370172))`
> 	const polygon5 = `POLYGON ((157.0188155006617308 268.8332448475994170, 157.0188155006617308 403.2498672713991255, 314.0376310013234615 403.2498672713991255, 314.0376310013234615 268.8332448475994170, 157.0188155006617308 268.8332448475994170))`
> 
> 	// ...
>   
> 	poly4, _ := wkt.UnmarshalString(polygon4)
> 	poly5, _ := wkt.UnmarshalString(polygon5)
> 
> 	tests := []TestStruct{
> 		// ...
> 		{name: "notcontain", args: args{
> 			g1: poly4,
> 			g2: poly5,
> 		}, want: false, wantErr: false},
> 	}
> 	for _, tt := range tests {
> 		t.Run(tt.name, func(t *testing.T) {
> 			G := NormalStrategy()
> 			got, err := G.Contains(tt.args.g1, tt.args.g2)  // true
> 			if (err != nil) != tt.wantErr {
> 				t.Errorf("Contains() error = %v, wantErr %v", err, tt.wantErr)
> 				return
> 			}
> 			if got != tt.want {
> 				t.Errorf("Contains() got = %v, want %v", got, tt.want)
> 			}
> 		})
> 	}
> }
> ```
> 
> The result returned is `true`.
> 
> However, when I used a visualization tool for verification, I found that the results were wrong.
> 
> As `polygon4` shown in the pictures，
> 
> ![image-20220208111053447](https://camo.githubusercontent.com/53fd9612420bacc7275ff304a8143dc7493414e8d9bbebcb3edc42930f492665/68747470733a2f2f796966742d626c6f672d313330303035313836332e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f626c6f672f696d6167652d32303232303230383131313035333434372e706e67)
> 
> and `polygon5` shown：
> 
> ![image-20220208111318482](https://camo.githubusercontent.com/8ea2784c3181b1ce44c15955fe9f2f1039d332352a3c5cbdcbd9bb4e76cc5ce6/68747470733a2f2f796966742d626c6f672d313330303035313836332e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f626c6f672f696d6167652d32303232303230383131313331383438322e706e67)
> 
> The relationship between these 2 shapes is：
> 
> ![image-20220208111459125](https://camo.githubusercontent.com/cbe849d78ae305305932567b3c8d2e2f4474bcdc569ddb3f432fc70b138621c1/68747470733a2f2f796966742d626c6f672d313330303035313836332e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f626c6f672f696d6167652d32303232303230383131313435393132352e706e67)
> 
> Obviously `not contained`.
> 
> THX~

ok,we will fix it recently

**Comment by xiaogu-space** [comment]
@Mamba2Yi we have fix the contain fun bug in this pull https://github.com/spatial-go/geoos/pull/61
