### ISSUE TITLE
存在内存泄漏问题和空指针问题

### ISSUE THREAD

**Issue by ziyunhai** [spatial-go/geoos#6]
在项目中使用到这个库，开发环境突然内存暴涨到25GB，经排查发现存在内存泄漏和空指针问题，望各位大牛查验。

在`geoos/geo/wkt.go` 中的

```
// DecodeWKTToStr decode GEOSGeometry to WKT string
func DecodeWKTToStr(writer GEOSWKTWriter, g GEOSGeometry) (string, error) {
	cstr := C.GEOSWKTWriter_write_r(geosContext, writer, g)
	if cstr == nil {
		return "", errors.New("writer to wkt is null")
	}
	return C.GoString(cstr), nil
}

```

需要更新为

```
// DecodeWKTToStr decode GEOSGeometry to WKT string
func DecodeWKTToStr(writer GEOSWKTWriter, g GEOSGeometry) (string, error) {
	cstr := C.GEOSWKTWriter_write_r(geosContext, writer, g)
	if cstr == nil {
		return "", errors.New("writer to wkt is null")
	}

	strTmp := C.GoString(cstr) 
	C.free(unsafe.Pointer(cstr)) //cstr 内存释放，不然会出现内存泄漏
	return strTmp, nil
}
```

在geoos/planar/strategy_geos.go中，很多类似方法存在空指针，导致panic，以Union为例：

```
func Union(g1 string, g2 string) (string, error) {
	geom1, geom2 := convertWKTtoGEOSGeometry(g1, g2)
	defer func() {
		C.GEOSGeom_destroy_r(geosContext, geom1)
		C.GEOSGeom_destroy_r(geosContext, geom2)
	}()
	g := C.GEOSUnion_r(geosContext, geom1, geom2)
	wkt, e := ToWKTStr(g)
	if e != nil {
		return "", e
	}
	return wkt, nil
}

```

需要更新为

```
func Union(g1 string, g2 string) (string, error) {
	geom1, geom2 := convertWKTtoGEOSGeometry(g1, g2)
	defer func() {
		C.GEOSGeom_destroy_r(geosContext, geom1)
		C.GEOSGeom_destroy_r(geosContext, geom2)
	}()
	g := C.GEOSUnion_r(geosContext, geom1, geom2)
        if g ==nil { //g 为空指针判断
               return "", errors.New("Union Geometry is   null")
        }
       defer func() {
		C.GEOSGeom_destroy_r(geosContext, g)   //释放g，不然会出现内存泄漏
	}()
	wkt, e := ToWKTStr(g)
	if e != nil {
		return "", e
	}
	return wkt, nil
}
```

**Comment by tianpf** [comment]
非常感谢，我们会尽快检查和修复这个问题。

谢谢！

发件人: ziyunhai <notifications@github.com>
答复: spatial-go/geoos <reply@reply.github.com>
日期: 2021年2月9日 星期二 上午9:20
收件人: spatial-go/geoos <geoos@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [spatial-go/geoos] 存在内存泄漏问题和空指针问题 (#6)


在项目中使用到这个库，开发环境突然内存暴涨到25GB，经排查发现存在内存泄漏和空指针问题，望各位大牛查验。

在geoos/geo/wkt.go 中的
// DecodeWKTToStr decode GEOSGeometry to WKT string func DecodeWKTToStr(writer GEOSWKTWriter, g GEOSGeometry) (string, error) { cstr := C.GEOSWKTWriter_write_r(geosContext, writer, g) if cstr == nil { return "", errors.New("writer to wkt is null") } return C.GoString(cstr), nil }
需要更新为

`
// DecodeWKTToStr decode GEOSGeometry to WKT string
func DecodeWKTToStr(writer GEOSWKTWriter, g GEOSGeometry) (string, error) {
cstr := C.GEOSWKTWriter_write_r(geosContext, writer, g)
if cstr == nil {
return "", errors.New("writer to wkt is null")
}

strTmp := C.GoString(cstr)



C.free(unsafe.Pointer(cstr))



return strTmp, nil



}
在geoos/planar/strategy_geos.go中，很多类似方法存在空指针，导致panic，以Union为例：
func Union(g1 string, g2 string) (string, error) {
geom1, geom2 := convertWKTtoGEOSGeometry(g1, g2)
defer func() {
C.GEOSGeom_destroy_r(geosContext, geom1)
C.GEOSGeom_destroy_r(geosContext, geom2)
}()
g := C.GEOSUnion_r(geosContext, geom1, geom2)
wkt, e := ToWKTStr(g)
if e != nil {
return "", e
}
return wkt, nil
}

`

需要更新为

func Union(g1 string, g2 string) (string, error) { geom1, geom2 := convertWKTtoGEOSGeometry(g1, g2) defer func() { C.GEOSGeom_destroy_r(geosContext, geom1) C.GEOSGeom_destroy_r(geosContext, geom2) }() g := C.GEOSUnion_r(geosContext, geom1, geom2) if g ==nil { return return "", errors.New("Union Geometry is null") } wkt, e := ToWKTStr(g) if e != nil { return "", e } return wkt, nil }

**Comment by coolwxb** [comment]
@ziyunhai 感谢您的反馈，我们已安排人手排查问题并在近期fix这个issue。
