### ISSUE TITLE
An issue of PolygonOverlay.Union()

### ISSUE THREAD

**Issue by fonto86** [spatial-go/geoos#62]
When I used `PolygonOverlay.Union()` to find the union of two POLYGON, the result returned was as follows, which is different from the result I expected. 

<img src="https://yift-blog-1300051863.cos.ap-guangzhou.myqcloud.com/blog/image-20220310114034258-20220310135214833.png" alt="image-20220310114034258" style="zoom:40%;" />

The union I understand should be the result of the following.

<img src="https://yift-blog-1300051863.cos.ap-guangzhou.myqcloud.com/blog/image-20220310114121711.png" alt="image-20220310114121711" style="zoom:40%;" />

```go
func TestPolygonOverlay_Union(t *testing.T) {
	type fields struct {
		PointOverlay  *PointOverlay
		subjectPlane  *Plane
		clippingPlane *Plane
	}
	tests := []struct {
		name    string
		fields  fields
		want    []matrix.Steric
		wantErr bool
	}{
		{"poly poly", fields{PointOverlay: &PointOverlay{matrix.PolygonMatrix{{{0, 0}, {10, 0}, {10, 10}, {0, 10}, {0, 0}}},
			matrix.PolygonMatrix{{{5, 5}, {15, 5}, {15, 15}, {5, 15}, {5, 5}}},
		}},
			[]matrix.Steric{matrix.PolygonMatrix{{{5, 10}, {0, 10}, {0, 0}, {10, 0}, {10, 5}, {15, 5}, {15, 15}, {5, 15}, {5, 10}}}}, false},
	}
	for _, tt := range tests {
		if !geoos.GeoosTestTag && tt.name != "poly poly03" {
			continue
		}
		t.Run(tt.name, func(t *testing.T) {
			p := &PolygonOverlay{
				PointOverlay:  tt.fields.PointOverlay,
				subjectPlane:  tt.fields.subjectPlane,
				clippingPlane: tt.fields.clippingPlane,
			}
			got, err := p.Union()
                         // result:
                         // POLYGON((0 0,15 0,15 15,0 15,0 0))
      
                         // want: 
                         // POLYGON ((10 0, 0 0, 0 10, 5 10, 5 15, 15 15, 15 5, 10 5, 10 0))     
			if (err != nil) != tt.wantErr {
				t.Errorf("PolygonOverlay.Union() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			// ...
		})
	}
}
```

**Comment by xiaogu-space** [comment]
OK,we have find the bug,and we are fixing it now.

**Comment by changebetter1** [comment]
intersection  also has bug.

POLYGON ((113.58270814000005 34.71557888104119, 113.58271043000005 34.73757297104119, 113.58271336086447 34.737580042999575, 113.5827204344234 34.737582969999025, 113.6046718644234 34.737573259999024, 113.60467893299956 34.73757032913553, 113.60468185999994 34.737563258958815, 113.60467956999994 34.715569158958814, 113.60467663913391 34.715562086998816, 113.60466956557204 34.71555916000098, 113.58271813557204 34.71556888000098, 113.58271106699881 34.71557181086609, 113.58270814000005 34.71557888104119))

POLYGON((113.58272043315301 34.737572973722635,113.60467185859878 34.7375632566498,113.60467414450156 34.75955780700805,113.58272272415182 34.75956752361057,113.58272043315301 34.737572973722635))

**Comment by tianpf** [comment]
#78 fixed.
