### ISSUE TITLE
Buffer distance unit

### ISSUE THREAD

**Issue by renard** [spatial-go/geoos#94]
What is the distance unit used in `Buffer` function?

I did some tests like:

```go
	ls := space.LineString{
		{2.073333263397217, 48.81027603149414},  // LFPZ
		{1.5225944519042969, 48.45795440673828}, // LFON
		{1.361388921737671, 48.705833435058594}, //LFOP
	}

	data, _ := geojson.NewGeometry(ls).MarshalJSON()
	v := "trip"
	fmt.Printf("var %s = %s;\nL.geoJSON(%s, {}).addTo(map);\n", v, data, v)

	bls := ls.Buffer(0.01, 4)

	bdata, _ := geojson.NewGeometry(bls).MarshalJSON()
	v = "btrip"
	fmt.Printf("var %s = %s;\nL.geoJSON(%s, {}).addTo(map);\n", v, bdata, v)
```

It looks like `0.01` creates a 1km buffer around the trip line.

When I compute a distance between 2 points like that:
```go
	d := measure.SpheroidDistance(
		space.Point{2.073333263397217, 48.81027603149414}.ToMatrix(),
		space.Point{1.5225944519042969, 48.45795440673828}.ToMatrix(),
	)
	fmt.Printf("d = %f\n", d/1000)
```
It looks like distance is in meters.

Can you please clarify?

Thanks in advance.

**Comment by gumap** [comment]
If coordinate system is Mercator，the distance is meters.
If coordinate system is latitude and longitude，can't use "Buffer",please use "BufferInMeter",the distance is meters.

**Comment by renard** [comment]
Indeed I saw `BufferInMeter` but it mangles the buffer.
I want to create route corridors and display them on a map using Leaflet which is supposed to use Mercator projection.

Here is the code I have:

```go
	ls := space.LineString{
		{2.073333263397217, 48.81027603149414},  // LFPZ
		{1.5225944519042969, 48.45795440673828}, // LFON
		{1.361388921737671, 48.705833435058594}, //LFOP
		{2.073333263397217, 48.81027603149414},  // LFPZ
		{2.0408332347869873, 49.0966682434082},  //LFPT
	}
	data, _ := geojson.NewGeometry(ls).MarshalJSON()
	v := "trip"
	fmt.Printf("var %s = %s;\nL.geoJSON(%s, {color: 'red'}).addTo(map);\n", v, data, v)

	bls := ls.BufferInMeter(1000, 10)
	//bls := ls.Buffer(0.025, 10)

	bdata, _ := geojson.NewGeometry(bls).MarshalJSON()
	v = "btrip"
	fmt.Printf("var %s = %s;\nL.geoJSON(%s, {}).addTo(map);\n", v, bdata, v)
```

On the map, the red is the route and the blue, the buffered corridor:
<img width="342" alt="Screen Shot 2023-04-07 at 10 46 28" src="https://user-images.githubusercontent.com/383821/230576535-4eddafbf-837c-44d2-901e-bd8b4458ff1f.png">

If I zoom a little bit we can see the buffer is not at equal distance from the route:
<img width="662" alt="Screen Shot 2023-04-07 at 10 49 14" src="https://user-images.githubusercontent.com/383821/230576843-be4caad1-5738-416c-970c-cc72e8584878.png">

Maybe I did something wrong. The coordinates are GPS coordinates (I guess the is mercator ones) but maybe I use spatial-go with lat/lon instead of Mercator because I see default coordinate system is `GCJ02`. Is there a way to change it to `WGS84`?



And an other point, when the route comes back over an existing point, there is a hole in the polygon:
<img width="412" alt="Screen Shot 2023-04-07 at 11 13 25" src="https://user-images.githubusercontent.com/383821/230581801-b088a42e-f837-4bd2-8030-5ec672986b23.png">

Is there a way to not create holes in that case?

Thanks for your support.

**Comment by hnybom** [comment]
I can concur I'm experiencing the same problem with the angels. It seems that the calculation doesn't take into account the first line of the LineString and the angle is just calculated based on the second one.. 
![image](https://user-images.githubusercontent.com/795413/231418642-042c6bda-1492-433d-96d4-9c4a97275f22.png)

**Comment by tianpf** [comment]
Thank you very much for your feedback. We will carefully consider your suggestions and respond to and solve them as soon as possible. If you have any other questions or needs, please feel free to contact us, and our team will do our best to serve you. Finally, thank you again for your support and trust in us.

**Comment by pipipizhuqaq** [comment]
BufferInMeter method we are trying to fix, thanks for using GeoOS.

**Comment by tianpf** [comment]
The new version has fixed bugs
